#!/usr/bin/env bash

WORK_DIR=/work

SCRIPT_DIR=$(dirname $0)
SESSION=$1
SUBJECT=${SESSION%_*}
INSTRUMENT=${SUBJECT#*_}
DATE=${SESSION##*_}
T1=$2
T2=$3
DMRI=$4

python $SCRIPT_DIR/qc_analysis.py --phantom t1_32ch "$T1" \
                                  --phantom t2_32ch "$T2" \
                                  --phantom dmri_32ch "$DMRI" \
                                  --dates $DATE \
                                  --instrument $INSTRUMENT \
                                  --work_dir $WORK_DIR
                                  
                                  